### PR TITLE
added translation example

### PR DESCRIPTION
**Pull request by rubenVerschueren**
example contains javascript and sample resource files

### CODE REVIEW

**Comment by HugoTrimp** [comment]
Hi Ruben, I'm a bit unclear about the purpose of this example, as skins already support localized include files. Could you explain?

**Comment by rubenVerschueren** [comment]
Hi Hugo,

In our skin we had needed to display some localize text. Originally we wanted to upload language resouce files (like in the documentation), but according to the support/helpdesk there was no way for us to get access to these uploaded resource files in our skin.

so if we would change a title in the resource we couldn't retrieve the title in the header or footer of our skin.

that's why we added our own simple resource file translation method.

**Comment by HugoTrimp** [comment]
Localized headers/footers can be achieved using e.g. cfooter_nl.txt. Did you consider this approach?

**Comment by rubenVerschueren** [comment]
Hugo,

Yes we did but it was simpler for our content editors to have separate files with the translations. If new languages are needed, they can add a translation file, without the risk of changing the layout. It also separates the layout and the text, so any layout changes can be done in one file.

**Pull request merged**
